---



- hosts: 10.116.0.2 , 10.116.0.4
  become: true
  user: mashraf
  tasks:


    - name: copying .vim direct.
      copy:
        src: /home/mashraf/vim.tar.xz
        dest: /home/mashraf/
        remote_src: no
        owner: mashraf
        group: mashraf
        mode: 0775
        


